export default [
    {
        files: ["**/*.js"],
        ignores: ["**/static/lib/**"],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: "module",
            globals: {
                // Browser globals
                window: "readonly",
                document: "readonly",
                navigator: "readonly",
                console: "readonly",
                setTimeout: "readonly",
                clearTimeout: "readonly",
                setInterval: "readonly",
                clearInterval: "readonly",
                ResizeObserver: "readonly",
                MutationObserver: "readonly",
                requestAnimationFrame: "readonly",
                cancelAnimationFrame: "readonly",
                fetch: "readonly",
                URL: "readonly",
                URLSearchParams: "readonly",
                localStorage: "readonly",
                sessionStorage: "readonly",
                location: "readonly",
                history: "readonly",
                Event: "readonly",
                CustomEvent: "readonly",
                HTMLElement: "readonly",
                Promise: "readonly",
                Map: "readonly",
                Set: "readonly",
                Blob: "readonly",
                FileReader: "readonly",
                MouseEvent: "readonly",
                DOMParser: "readonly",
                crypto: "readonly",
                performance: "readonly",
                // Odoo globals
                odoo: "readonly",
                owl: "readonly",
                odoo: "readonly",
                luxon: "readonly",
                // Third-party globals
                google: "readonly",
                turf: "readonly",
                deck: "readonly",
                markerClusterer: "readonly",
            },
        },
        rules: {
            "no-undef": "warn",
            "no-unused-vars": "off",
            "no-console": "off",
            "no-debugger": "error",
            "prefer-const": "warn",
            "no-var": "error",
            "eqeqeq": ["error", "always"],
            "semi": ["error", "always"],
        },
    },
];